// This file is auto-generated by @hey-api/openapi-ts

import type {
  GetMessagesResponse,
  GetThreadMessagesResponse,
} from './types.gen';

export const getMessagesResponseTransformer = async (
  data: any,
): Promise<GetMessagesResponse> => {
  if (data.messages) {
    data.messages = data.messages.map((item: any) => {
      if (item.created_at) {
        item.created_at = new Date(item.created_at);
      }
      return item;
    });
  }
  return data;
};

export const getThreadMessagesResponseTransformer = async (
  data: any,
): Promise<GetThreadMessagesResponse> => {
  if (data.messages) {
    data.messages = data.messages.map((item: any) => {
      if (item.created_at) {
        item.created_at = new Date(item.created_at);
      }
      return item;
    });
  }
  return data;
};
